char *make_path(char *path);
char *get_relative_filename(char *base_path, char *abs_name);
char *join_path_and_name(char *path, char *name);
int files_are_same(char *filename1, char *filename2);
int get_window_height(WINDOW *window);
int get_window_width(WINDOW *window);
char *truncate_string(char *string, int length);
char *comma_number(long number);
char *get_full_path(char *path, char *base_path);
char *get_parent_path(char *path);
char *get_name(char *path);
char *mode_string(mode_t mode);
int is_number (char *str);
int get_uid(char *user, uid_t *uid);
int get_gid(char *group, gid_t *gid);
char *date_string(time_t time, char *format);
char *time_string(time_t time, char *format);
char file_type_letter(long bits);
char *file_type_string(long bits, int abbreviated);
int get_fs_blocksize(char *path, int *blocksize);
int get_fs_freek(char *path, long *freek);
char *parse_chown_string(char *chown_string, int *uid, int *gid);
